package fr.eni.projet_encheres.dal.jdbc;

import fr.eni.projet_encheres.bo.ArticleVendu;
import fr.eni.projet_encheres.bo.Categorie;
import fr.eni.projet_encheres.dal.DALException;
import fr.eni.projet_encheres.dal.dao.DAOArticleVendu;
import fr.eni.projet_encheres.dal.ErrorCodesDAL;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ArticleVenduDAOJdbcImpl implements DAOArticleVendu {
    /**
     * Insert an instance into the DB and fill this instance with the id generated by mssql server
     * @param  articleVendu ArticleVendu The instance to insert into the DB
     * @throws DALException if the SQL INSERT request is wrong
     */
    @Override
    public void insert(ArticleVendu articleVendu) throws DALException {
        Connection cnx = JdbcTools.connect();
        try {
            String INSERT = "INSERT INTO ARTICLES_VENDUS " +
                    "(nom_article, description, date_debut_encheres, date_fin_encheres, prix_initial, prix_vente, etat_vente, no_utilisateur, no_categorie) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = cnx.prepareStatement(INSERT, PreparedStatement.RETURN_GENERATED_KEYS);
            fillPreparedStatement(articleVendu, stmt);
            stmt.executeUpdate();
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                articleVendu.setNoArticle(rs.getInt(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_INSERT);
            throw dalException;
        }
    }

    @Override
    public ArticleVendu selectById(int id) throws DALException {
        return null;
    }

    /**
     * Get all ArticleVendu instances that match a category from the DB
     * @param categorie the filter
     * @return an ArrayList filled with instances
     * @throws DALException if the SQL SELECT request is wrong
     */
    @Override
    public List<ArticleVendu> filterByCategory(Categorie categorie) throws DALException {
        Connection cnx = JdbcTools.connect();
        List<ArticleVendu> articlesVendus = new ArrayList<>();
        try {
            String SELECT_BY_CATEGORY = "SELECT * " +
                    "FROM ARTICLES_VENDUS " +
                    "INNER JOIN CATEGORIES C on ARTICLES_VENDUS.no_categorie = C.no_categorie " +
                    "WHERE C.no_categorie = ?";
            PreparedStatement stmt = cnx.prepareStatement(SELECT_BY_CATEGORY);
            stmt.setInt(1, categorie.getNoCategorie());
            stmt.execute();
            ResultSet rs =  stmt.getResultSet();
            while (rs.next()) {
                articlesVendus.add(hydrateArticleVendu(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_SELECT);
            throw dalException;
        }
        return articlesVendus;
    }

    public List<ArticleVendu> filterByEtat(String etat) throws DALException {
        Connection cnx = JdbcTools.connect();
        List<ArticleVendu> articlesVendus = new ArrayList<>();
        try {
            String SELECT_BY_ETAT = "SELECT * FROM ARTICLES_VENDUS WHERE etat_vente = ?";
            PreparedStatement stmt = cnx.prepareStatement(SELECT_BY_ETAT);
            stmt.setString(1, etat);
            stmt.execute();
            ResultSet rs = stmt.getResultSet();
            while (rs.next()) {
                articlesVendus.add(hydrateArticleVendu(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_SELECT);
            throw dalException;
        }
        return articlesVendus;
    }

    /**
     *
     * Get all ArticleVendu instances that the field no_article match a String from the DB
     * @param filter the filter
     * @return An ArrayList filled with instances
     * @throws DALException if the SQL SELECT request is wrong
     */
    @Override
    public List<ArticleVendu> filterByString(String filter) throws DALException {
        Connection cnx = JdbcTools.connect();
        List<ArticleVendu> articlesVendus = new ArrayList<>();
        try {
            String SELECT_BY_NAME_SEARCH = "SELECT * " +
                    "FROM ARTICLES_VENDUS " +
                    "WHERE nom_article LIKE ?";
            PreparedStatement stmt = cnx.prepareStatement(SELECT_BY_NAME_SEARCH);
            stmt.setString(1, "%" + filter + "%");
            stmt.execute();
            ResultSet rs = stmt.getResultSet();
            while(rs.next()) {
                articlesVendus.add(hydrateArticleVendu(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_SELECT);
            throw dalException;
        }
        return articlesVendus;
    }
    /**
     * Select all the articleVendu from the DB
     * @return An ArrayList filled with instances of Utilisateur
     */
    @Override
    public List<ArticleVendu> selectAll() throws DALException {
        Connection cnx = JdbcTools.connect();
        List<ArticleVendu> articlesVendus = new ArrayList<>();
        try {
            String SELECT_ALL = "SELECT * FROM ARTICLES_VENDUS";
            PreparedStatement stmt = cnx.prepareStatement(SELECT_ALL);
            stmt.execute();
            ResultSet rs = stmt.getResultSet();
            while (rs.next()) {
                articlesVendus.add(hydrateArticleVendu(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_SELECT);
            throw dalException;        }
        return articlesVendus;
    }

    @Override
    public void update(ArticleVendu articleVendu) throws DALException {

    }

    @Override
    public void delete(ArticleVendu articleVendu) throws DALException {

    }
    /**
     * Set a prepared statement used by both INSERT and UPDATE requests
     * @param articleVendu The instance to insert or update
     * @param stmt Statement The statement to set
     * @throws SQLException If parameterIndex does not correspond to a parameter marker in the SQL statement
     */
    private void fillPreparedStatement(ArticleVendu articleVendu, PreparedStatement stmt) throws SQLException {
        stmt.setString(1, articleVendu.getNomArticle());
        stmt.setString(2, articleVendu.getDescription());
        // https://stackoverflow.com/questions/6777810/a-datetime-equivalent-in-java-sql-is-there-a-java-sql-datetime
        stmt.setObject(3, new Timestamp(articleVendu.getDateDebutEncheres().getTime()));
        stmt.setObject(4, new Timestamp(articleVendu.getDateFinEncheres().getTime()));
        stmt.setInt(5, articleVendu.getPrixInitial());
        stmt.setInt(6, articleVendu.getPrixVente());
        stmt.setString(7, articleVendu.getEtatVente());
        stmt.setInt(8, articleVendu.getNoUtilisateur());
        stmt.setInt(9, articleVendu.getNoCategorie());
    }
    /**
     * Fill an instance from a ResultSet
     * @param rs the resultSet
     * @return articleVendu The instance
     * @throws SQLException if the ResultSet doesn't match the different fields
     */
    private ArticleVendu hydrateArticleVendu(ResultSet rs) throws SQLException {
        return new ArticleVendu(
                rs.getInt("no_article"),
                rs.getString("nom_article"),
                rs.getString("description"),
                rs.getDate("date_debut_encheres"),
                rs.getDate("date_fin_encheres"),
                rs.getInt("prix_initial"),
                rs.getInt("prix_vente"),
                rs.getString("etat_vente"),
                rs.getInt("no_utilisateur"),
                rs.getInt("no_categorie")
        );
    }


}
