package fr.eni.projet_encheres.dal.jdbc;

import fr.eni.projet_encheres.bo.Retrait;
import fr.eni.projet_encheres.dal.DALException;
import fr.eni.projet_encheres.dal.DAO;
import fr.eni.projet_encheres.dal.ErrorCodesDAL;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class RetraitDAOJdbcImpl implements DAO<Retrait> {
    /**
     * Insert an instance into the DB and fill this instance with the id generated by mssql server
     * @param  retrait Retrait The instance to insert into the DB
     * @throws DALException if the SQL INSERT request is wrong
     */
    @Override
    public void insert(Retrait retrait) throws DALException {
        Connection cnx = JdbcTools.connect();
        try {
            String INSERT = "INSERT INTO RETRAITS (no_article, rue, code_postal, ville) VALUES (?, ?, ?, ?)";
            PreparedStatement stmt = cnx.prepareStatement(INSERT);
            stmt.setInt(1, retrait.getNoArticle());
            stmt.setString(2, retrait.getRue());
            stmt.setString(3, retrait.getCodePostal());
            stmt.setString(4, retrait.getVille());
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            DALException dalException = new DALException();
            dalException.addError(ErrorCodesDAL.ERROR_SQL_INSERT);
            throw dalException;
        }
    }
    /**
     * Extract data from the DB by id
     * @param noArticle int The primary key of the Retrait to extract from the DB
     * @return retrait An instance of the retrait
     * @throws DALException if the SQL INSERT request is wrong
     */
    @Override
    public Retrait selectById(int noArticle) throws DALException {
        Connection cnx = JdbcTools.connect();
        String SELECT_BY_ID = "SELECT * FROM RETRAITS WHERE no_article = ?";
        try {
            PreparedStatement stmt = cnx.prepareStatement(SELECT_BY_ID);
            stmt.setInt(1, noArticle);
            stmt.execute();
            ResultSet rs = stmt.getResultSet();
            if (rs.next()) {

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return null;
    }

    @Override
    public List<Retrait> selectAll() throws DALException {
        return null;
    }

    @Override
    public void update(Retrait retrait) throws DALException {

    }

    @Override
    public void delete(Retrait retrait) throws DALException {

    }

    /**
     * Fill an instance from a ResultSet
     * @param rs the ResultSet
     * @return Retrait the instance
     * @throws SQLException if the ResultSet doesn't match the different fields
     */
    private Retrait hydrateRetrait(ResultSet rs) throws SQLException {
        return new Retrait(
                rs.getInt("no_article"),
                rs.getString("rue"),
                rs.getString("code_postal"),
                rs.getString("ville")
        );
    }
}
